global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['warehouse_api:8000']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb_exporter:9216']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka_exporter:9308']
